services:
  api-web-for-react:
    container_name: api-web-for-react
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 4000:8080
      - 5005:5005
    depends_on:
      - api-db-for-react
    networks:
      - jr_backend
    volumes:
      - ../:/app
  api-db-for-react:
    container_name: api-db-for-react
    platform: linux/amd64
    image: mysql:8.4.2
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - jr-api-db:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - jr_backend

networks:
  jr_backend:
volumes:
  jr-api-db:

